[project]
name = "bachelor-thesis-sml"
version = "0.1.0"
description = "Project for benchmarking and deloping model merging methods for my bachelor thesis at the ETH Statistical Machine Learning Lab (SML)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
